module.exports = {
  extends: ['eslint:recommended', 'plugin:prettier/recommended', 'standard'],
  parser: 'babel-eslint',
  parserOptions: {
    ecmaVersion: 8,
    sourceType: 'module',
  },
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  plugins: ['standard', 'promise'],
  rules: {
    'import/no-webpack-loader-syntax': 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'comma-style': 'error',
    eqeqeq: 'warn',
    'guard-for-in': 'error',
    'keyword-spacing': 'error',
    'lines-between-class-members': ['error', 'always'],
    'max-nested-callbacks': ['error', 3],
    'newline-per-chained-call': 'error',
    'no-console': 'off',
    'no-else-return': 'error',
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-lonely-if': 'error',
    'no-new-func': 'error',
    'no-shadow-restricted-names': 'error',
    'no-trailing-spaces': 'error',
    'no-undef-init': 'error',
    'no-useless-concat': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-spread': 'error',
    'prettier/prettier': [
      'error',
      {
        semi: false,
        singleQuote: true,
        trailingComma: 'all',
      },
    ],
    radix: 'error',
    semi: ['error', 'never'],
    'space-before-function-paren': [
      'error',
      {
        anonymous: 'never',
        asyncArrow: 'always',
        named: 'never',
      },
    ],
    strict: ['error', 'never'],
  },
}
